collections:
    One:
      output: true
    Two:
      output: true
    Three:
      output: true
    Four:
      output: true
    Five:
      output: true
    Six:
      output: true
    Seven:
      output: true
    Eight:
      output: true
    Nine:
      output: true
    Ten:
      output: true
    Eleven:
      output: true
    Twelve:
      output: true
    contributors:
      output: true
   

# Site settings
title: വിദ്യാലയം.online  
baseuri: https://vidhyalayam.online/
email: info@vidhyalayam.online
description: വിദ്യാലയം.online
smContent: A simple & intuitive web portal to access Kerala State syllabus Videos & Textbooks published by KITE Victor Channel /SCERT Kerala. The video lessons and textbooks are arranged class and subject wise for easy access
baseurl:
url: https://vidhyalayam.online/
company: വിദ്യാലയം.online

#Heading 
Head1: Vidhyalayam
Head2: വിദ്യാധനം സർവ്വധനാൽ പ്രധാനം 
Head3: 
HeadCTA: 
HeadCTALink: 
#Call to action
USPH: വിദ്യാലയം.online 
USP:  A simple & intuitive web portal to access Kerala State syllabus Videos & Textbooks published by KITE Victor Channel /SCERT Kerala. The video lessons and textbooks are arranged class and subject wise for easy access. Our portal is accessible across any low end to high-end smartphones, tablets, and desktops/laptops without any additional installation. As per our policy, we also refrain from showcasing any advertisements on our website. We are a group of volunteers mostly students intended to serve the student/teachers community in Kerala. If you are interested in volunteering with us and contributing back to our society please do email us at volunteering(at)vidhyalayam.online. We looking for both technical, non-technical volunteers and teachers.
TContentH: 
TContentB: 
TContentLink: 



FeatureHeading:  

Feature1H:  
Feature1: 
Feature2H: 
Feature2: 

Feature3H:  
Feature3: 

Feature4H: 
Feature4: 
#Clinets
clinetsH : 
#Portfolio

portfolioHeader : 
portfolioHeaderA: 
portfolioHeaderLink: 
portfolioHeaderB :  
portfolioHeaderBN: 
portfolioHeaderB1: 
portfolioHeaderB1C: 
#Ribbon 
RHead1: 
RHead2: 
RHead3: 
RCTA:  

ph_number: 
github_username: 

footer:   2020  www.vidhyalayam.github.io



# Build settings
markdown: kramdown


