collections:
    Nine:
      output: true
   

# Site settings
title: വിദ്യാലയം.online  
baseuri: https://vidhyalayam.github.io/
email: info@quadralogics.com
description: വിദ്യാലയം.online
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
company: QuadraLogics
#Heading 
Head1: വിദ്യാലയം 
Head2: .online
Head3: 
HeadCTA: 
HeadCTALink: 
#Call to action
USPH: വിദ്യാലയം.online 
USP: We are a group of volunteers collating videos published by Kerala Infrastructure and Technology for Education (KITE) Victor channel,  to enable easier access to students. The Videos are collated and arranged by class and subject wise so that a student can easily access the content

TContentH: 
TContentB: 
TContentLink: 

#services
ServicesHeading:  

Services1H: 
Services1: 
Services2H: 
Services2: 

Services3H: 
Services3: 

Services4H:  
Services4: 

#features 

FeatureHeading:  

Feature1H:  
Feature1: 
Feature2H: 
Feature2: 

Feature3H:  
Feature3: 

Feature4H: 
Feature4: 
#Clinets
clinetsH : 
#Portfolio

portfolioHeader : 
portfolioHeaderA: 
portfolioHeaderLink: 
portfolioHeaderB :  
portfolioHeaderBN: 
portfolioHeaderB1: 
portfolioHeaderB1C: 
#Ribbon 
RHead1: 
RHead2: 
RHead3: 
RCTA:  

ph_number: 
github_username: 

footer:   2020  www.vidhyalayam.github.io



# Build settings
markdown: kramdown


