collections:
    One:
      output: true
    Two:
      output: true
    Three:
      output: true
    Four:
      output: true
    Five:
      output: true
    Six:
      output: true
    Seven:
      output: true
    Eight:
      output: true
    Nine:
      output: true
    Ten:
      output: true
    Eleven:
      output: true
    Twelve:
      output: true
    contributors:
      output: true
   

# Site settings
title: വിദ്യാലയം.online  
baseuri: https://vidhyalayam.github.io/
email: info@quadralogics.com
description: വിദ്യാലയം.online
baseurl: https://vidhyalayam.github.io/
url: https://vidhyalayam.github.io/
company: QuadraLogics
#Heading 
Head1: വിദ്യാലയം 
Head2: .online
Head3: 
HeadCTA: 
HeadCTALink: 
#Call to action
USPH: വിദ്യാലയം.online 
USP: We are a group of volunteers collating videos published by Kerala Infrastructure and Technology for Education (KITE) Victor channel,  to enable easier access to students. The Videos are collated and arranged by class and subject wise so that a student can easily access the content

TContentH: 
TContentB: 
TContentLink: 

#services
ServicesHeading:  Free Education for All

Services1H: 1000+ videos
Services1: This portal contains access to 1000+ video lessons released by KITES Victors channel. The videos from 1 to 12 Standard are tagged and arranged subject-wise in chronological order to enable easy access to students and teachers.
Services2H: Free of Cost 
Services2: We are a group of volunteers and our intention to sever the student's community. Hence we don't charge for any of our services.  Please feel free to share your feedback so that we can serve even better.

Services3H: No Advertisements 
Services3: Advertisements act as real distractors for students during online learning, Hence we don't have any Advertisements on our website. We neither do generate any review nor incur many costs hence we don't take any donations either.

Services4H: Accessibility  
Services4: The video content can be accessed across any device from low-end mobile devices to tablets or Desktop/Laptops. Our Volunteers have put their hearts to ensure you can access these videos across any devices with a simple and elegant UX.

Services5H: Open Source  
Services5: Our program is under Open Source. We use Github to store our source code, collaborate, and deploy. if Interested in contributing back to the society please do email us at. We looking for both technical, non-technical volunteers and teachers.

#features 

FeatureHeading:  

Feature1H:  
Feature1: 
Feature2H: 
Feature2: 

Feature3H:  
Feature3: 

Feature4H: 
Feature4: 
#Clinets
clinetsH : 
#Portfolio

portfolioHeader : 
portfolioHeaderA: 
portfolioHeaderLink: 
portfolioHeaderB :  
portfolioHeaderBN: 
portfolioHeaderB1: 
portfolioHeaderB1C: 
#Ribbon 
RHead1: 
RHead2: 
RHead3: 
RCTA:  

ph_number: 
github_username: 

footer:   2020  www.vidhyalayam.github.io



# Build settings
markdown: kramdown


